local s,id=GetID()
function s.initial_effect(c)
	Kirafan2.CreamateCharacter(c)
	local e5=Effect.CreateEffect(c)
	e5:SetType(EFFECT_TYPE_IGNITION)
	e5:SetRange(LOCATION_MZONE)
	e5:SetProperty(EFFECT_FLAG_CARD_TARGET)
	e5:SetCost(Kirafan2.dottecost2)
	e5:SetOperation(s.op)
	c:RegisterEffect(e5)
    local e6=e5:Clone()
	e6:SetType(EFFECT_TYPE_QUICK_O)
	e6:SetCode(EVENT_FREE_CHAIN)
	e6:SetCondition(Kirafan6.spcreamatecon)
	c:RegisterEffect(e6)
end
function s.op(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local tg=c:GetOverlayGroup()
	local dotte=Duel.GetFieldGroupCount(tp,LOCATION_GRAVE,0)
	Duel.Remove(tg,POS_FACEUP,REASON_RULE)
	Duel.Remove(c,POS_FACEUP,REASON_RULE)
	local nadeshiko=Duel.CreateToken(tp,10052133)
	Duel.SpecialSummon(nadeshiko,0,tp,tp,false,false,POS_FACEUP_ATTACK)
end
